import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Socials from "@/components/Socials";
import Footer from "@/components/Footer";
import { Headshot } from "@/components/Navbar/src/styled";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Milan Kubala</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Socials />
      <Footer />
      <h1>Milan Kubala</h1>
      <p>Frontend Developer, redaktor, editor</p>
      <Headshot>
        <Image
          src={"/imgs/headshot01-right-sm.png"}
          width={900}
          height={900}
          alt="Milan Kubala"
        />
      </Headshot>
    </>
  );
}
