import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Socials from "@/components/Socials";
import Footer from "@/components/Footer";

import { styled } from "styled-components";

const inter = Inter({ subsets: ["latin"] });

const headshot = {
  size: {
    PC: "220px",
    M: "100px",
  },
};

const PageContainer = styled.div`
  width: calc(100vw - 360px);
  height: calc(100vh - 220px);
  padding-left: 120px;

  position: relative;
  display: flex;
  flex-direction: row;
  align-items: center;

  .text {
    height: 220px;
    padding-left: 250px;
    padding-right: 60px;
    border-radius: 110px;

    display: flex;
    flex-direction: column;
    justify-content: center;
    color: white;
    font: 1.5em Source Sans Pro;

    background-color: rgba(255, 255, 255, 0.1);
    h1,
    p {
      margin: 0;
    }
  }
`;

const HeaderContainer = styled.div`
  position: relative;
`;

const Headshot = styled.div`
  margin: 0px;
  width: ${headshot.size.PC};
  height: ${headshot.size.PC};
  border-radius: 100%;
  overflow: hidden;
  background: white;

  position: absolute;
  left: 0;
  top: 0;

  img {
    width: 100%;
    height: auto;
  }
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Milan Kubala</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Socials />
      <Footer />
      <PageContainer>
        <HeaderContainer>
          <Headshot>
            <Image
              src={"/imgs/headshot01-right-sm.png"}
              width={900}
              height={900}
              alt="Milan Kubala"
            />
          </Headshot>
          <div className="text">
            <h1>Milan Kubala</h1>
            <p>React developer / Redaktor / Editor</p>
          </div>
        </HeaderContainer>
      </PageContainer>
    </>
  );
}
